; ============================================================
; Password Manager - Inno Setup 6 Installer Script
; ============================================================
; 
; PREREQUISITES:
;   1. Run: npm run pack:win
;      This builds the Electron app into dist-electron\win-unpacked\
;   2. Compile with:
;      "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
;
; OUTPUT: dist-electron\PasswordManagerSetup.exe
; ============================================================

#define MyAppName      "Password Manager"
#define MyAppVersion   "1.0.0"
#define MyAppPublisher "Nyx"
#define MyAppExeName   "PasswordManager.exe"
#define MyAppId        "{{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}"
#define SourceDir      "dist-electron\win-unpacked"
#define DesktopDir     "desktop"
#define ExtId          "nionddfgmkmbjlchgmmmajifhkfhijhh"

[Setup]
; --- Identity ---
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL=https://github.com/
AppSupportURL=https://github.com/
AppUpdatesURL=https://github.com/

; --- Installation directory ---
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes

; --- Output ---
OutputDir=dist-electron
OutputBaseFilename=PasswordManagerSetup
Compression=lzma2/ultra64
SolidCompression=yes
InternalCompressLevel=ultra64

; --- Appearance ---
WizardStyle=modern
SetupIconFile=build\icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

; --- Privileges: install per-user so no UAC prompt needed for registry ---
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; --- Restart: not needed ---
RestartIfNeededByRun=no

; --- Allow upgrade without uninstalling first ---
CloseApplications=force
CloseApplicationsFilter=*{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: checkedonce
Name: "startuprun";  Description: "Start Password Manager with &Windows (runs in tray)"; GroupDescription: "Startup:"; Flags: unchecked

[Dirs]
; The desktop subfolder holds the native host scripts and generated manifests
Name: "{app}\desktop"

[Files]
; ── Full Electron app bundle (from npm run pack:win) ─────────────────────────
; Contains: PasswordManager.exe, Electron runtime dlls,
; resources\app.asar (all app code), and extension\ folder
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; ── nativeHost.cjs must live as a real file outside the asar ─────────────────
; The browser's native messaging spawns this file directly via the .bat wrapper.
Source: "{#DesktopDir}\nativeHost.cjs"; DestDir: "{app}\desktop"; Flags: ignoreversion solidbreak

[Icons]
; Start Menu
Name: "{group}\{#MyAppName}";           Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

; Desktop shortcut (optional task)
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

; Startup (optional task) - launch minimized to tray
Name: "{userstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startuprun

[Registry]
; ── Native Messaging Hosts ────────────────────────────────────────────────────
; The manifest JSON files are generated by the [Code] section's CurStepChanged
; procedure after all files are installed, so {app} is the real install path.

; Chrome
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\com.passwordmanager.host"; \
    ValueType: string; ValueName: ""; \
    ValueData: "{app}\desktop\com.passwordmanager.host.chrome.json"; \
    Flags: uninsdeletekey

; Edge
Root: HKCU; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\com.passwordmanager.host"; \
    ValueType: string; ValueName: ""; \
    ValueData: "{app}\desktop\com.passwordmanager.host.chrome.json"; \
    Flags: uninsdeletekey

; Opera
Root: HKCU; Subkey: "Software\Opera Software\NativeMessagingHosts\com.passwordmanager.host"; \
    ValueType: string; ValueName: ""; \
    ValueData: "{app}\desktop\com.passwordmanager.host.chrome.json"; \
    Flags: uninsdeletekey

; Firefox / Zen Browser
Root: HKCU; Subkey: "Software\Mozilla\NativeMessagingHosts\com.passwordmanager.host"; \
    ValueType: string; ValueName: ""; \
    ValueData: "{app}\desktop\com.passwordmanager.host.mozilla.json"; \
    Flags: uninsdeletekey

; ── IDM-style Extension Auto-Install ─────────────────────────────────────────
; Chrome/Edge read HKCU\Software\Google\Chrome\Extensions\<id>\update_url at
; startup and automatically prompt the user to enable the extension.
Root: HKCU; Subkey: "Software\Google\Chrome\Extensions\{#ExtId}"; \
    ValueType: string; ValueName: "update_url"; \
    ValueData: "https://clients2.google.com/service/update2/crx"; \
    Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Microsoft\Edge\Extensions\{#ExtId}"; \
    ValueType: string; ValueName: "update_url"; \
    ValueData: "https://clients2.google.com/service/update2/crx"; \
    Flags: uninsdeletekey

[Run]
; ── Offer to launch the app immediately after install ─────────────────────────
Filename: "{app}\{#MyAppExeName}"; \
    Description: "Launch {#MyAppName}"; \
    Flags: postinstall nowait skipifsilent

[UninstallRun]
; Nothing extra needed — all registry keys have Flags: uninsdeletekey above.

[Code]
// ─────────────────────────────────────────────────────────────────────────────
// Helper: write a plain text file using pure Pascal (no external process)
// ─────────────────────────────────────────────────────────────────────────────
procedure WriteFilePlain(const FileName, Content: string);
var
  Lines: TArrayOfString;
begin
  SetArrayLength(Lines, 1);
  Lines[0] := Content;
  SaveStringsToFile(FileName, Lines, False);
end;

// Helper: escape backslashes for embedding in JSON strings
function EscapeBackslashes(const S: string): string;
var
  I: Integer;
  Result2: string;
begin
  Result2 := '';
  for I := 1 to Length(S) do
  begin
    if S[I] = '\' then
      Result2 := Result2 + '\\'
    else
      Result2 := Result2 + S[I];
  end;
  Result := Result2;
end;

// ─────────────────────────────────────────────────────────────────────────────
// After all files are installed, generate the .bat wrapper and both
// native host manifest JSON files with the real install path baked in.
// This replaces the broken [Run] Electron approach entirely.
// ─────────────────────────────────────────────────────────────────────────────
procedure GenerateNativeHostFiles();
var
  AppDir:      string;
  DesktopDir:  string;
  BatPath:     string;
  ChromeJson:  string;
  MozillaJson: string;
  BatContent:  string;
  ChromeManifest: string;
  MozillaManifest: string;
begin
  AppDir     := ExpandConstant('{app}');
  DesktopDir := AppDir + '\desktop';
  BatPath    := DesktopDir + '\password-manager-host.bat';
  ChromeJson := DesktopDir + '\com.passwordmanager.host.chrome.json';
  MozillaJson := DesktopDir + '\com.passwordmanager.host.mozilla.json';

  // 1. Write the .bat wrapper that browsers will invoke via Native Messaging
  //    The BAT launches nativeHost.cjs using the Electron executable as the runtime.
  BatContent :=
    '@echo off' + #13#10 +
    '"' + AppDir + '\PasswordManager.exe" "' + DesktopDir + '\nativeHost.cjs"' + #13#10;
  WriteFilePlain(BatPath, BatContent);

  // 2. Write the Chromium native host manifest
  ChromeManifest :=
    '{' + #13#10 +
    '  "name": "com.passwordmanager.host",' + #13#10 +
    '  "description": "Password Manager Autofill Host",' + #13#10 +
    '  "path": "' + EscapeBackslashes(BatPath) + '",' + #13#10 +
    '  "type": "stdio",' + #13#10 +
    '  "allowed_origins": [' + #13#10 +
    '    "chrome-extension://nionddfgmkmbjlchgmmmajifhkfhijhh/"' + #13#10 +
    '  ]' + #13#10 +
    '}';
  WriteFilePlain(ChromeJson, ChromeManifest);

  // 3. Write the Mozilla/Firefox/Zen native host manifest
  MozillaManifest :=
    '{' + #13#10 +
    '  "name": "com.passwordmanager.host",' + #13#10 +
    '  "description": "Password Manager Autofill Host",' + #13#10 +
    '  "path": "' + EscapeBackslashes(BatPath) + '",' + #13#10 +
    '  "type": "stdio",' + #13#10 +
    '  "allowed_extensions": [' + #13#10 +
    '    "autofill@passwordmanager.com"' + #13#10 +
    '  ]' + #13#10 +
    '}';
  WriteFilePlain(MozillaJson, MozillaManifest);
end;

// ─────────────────────────────────────────────────────────────────────────────
// Hook into the installer steps — generate files right after installation done
// ─────────────────────────────────────────────────────────────────────────────
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    GenerateNativeHostFiles();
end;

// ─────────────────────────────────────────────────────────────────────────────
// Custom wizard page: explain the browser extension auto-install process
// {app} cannot be expanded in InitializeWizard (not yet initialized).
// We set the label body text in CurPageChanged instead, after {app} is known.
// ─────────────────────────────────────────────────────────────────────────────
var
  ExtPage:  TWizardPage;
  ExtTitle: TLabel;
  ExtLabel: TLabel;

procedure InitializeWizard();
begin
  ExtPage := CreateCustomPage(
    wpFinished,
    'Browser Extension Auto-Setup',
    'The Password Manager browser extension is being configured.'
  );

  ExtTitle := TLabel.Create(ExtPage);
  with ExtTitle do
  begin
    Parent     := ExtPage.Surface;
    Left       := 0;
    Top        := 0;
    Width      := ExtPage.SurfaceWidth;
    AutoSize   := False;
    Height     := 24;
    Font.Style := [fsBold];
    Caption    := 'Your browser extension will install automatically!';
  end;

  ExtLabel := TLabel.Create(ExtPage);
  with ExtLabel do
  begin
    Parent   := ExtPage.Surface;
    Left     := 0;
    Top      := 30;
    Width    := ExtPage.SurfaceWidth;
    Height   := ExtPage.SurfaceHeight - 30;
    WordWrap := True;
    // Caption is intentionally blank here — set in CurPageChanged below
    Caption  := '';
  end;
end;

// Populate the label body when our custom page is actually shown,
// at which point {app} is guaranteed to be initialized.
procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = ExtPage.ID then
    ExtLabel.Caption :=
      'For Google Chrome and Microsoft Edge:' + #13#10 +
      '  1. Close and reopen Chrome or Edge.' + #13#10 +
      '  2. A prompt will appear: "Password Manager Autofill was added."' + #13#10 +
      '  3. Click "Enable extension" — done! No ID copying required.' + #13#10 + #13#10 +
      'For Firefox and Zen Browser:' + #13#10 +
      '  1. Open about:debugging in your browser.' + #13#10 +
      '  2. Click "This Firefox" > "Load Temporary Add-on..."' + #13#10 +
      '  3. Select: ' + ExpandConstant('{app}') + '\extension\manifest.json' + #13#10 + #13#10 +
      'The native messaging bridge is automatically configured.' + #13#10 +
      'No manual setup or config file editing required!' + #13#10 + #13#10 +
      'Chrome/Edge Extension ID: nionddfgmkmbjlchgmmmajifhkfhijhh' + #13#10 +
      'Firefox/Zen Extension ID: autofill@passwordmanager.com';
end;
