/** Simple Icons slug per service id (bundled under src/assets/icons/). */
export const ICON_SLUGS: Record<string, string> = {
  facebook: "facebook",
  instagram: "instagram",
  x: "x",
  tiktok: "tiktok",
  snapchat: "snapchat",
  linkedin: "linkedin",
  pinterest: "pinterest",
  reddit: "reddit",
  discord: "discord",
  telegram: "telegram",
  whatsapp: "whatsapp",
  threads: "threads",
  gmail: "gmail",
  outlook: "microsoftoutlook",
  protonmail: "protonmail",
  icloud: "icloud",
  paypal: "paypal",
  revolut: "revolut",
  wise: "wise",
  crypto: "bitcoin",
  amazon: "amazon",
  ebay: "ebay",
  shopee: "shopee",
  alibaba: "alibabacloud",
  steam: "steam",
  epic: "epicgames",
  playstation: "playstation",
  xbox: "xbox",
  nintendo: "nintendo",
  riot: "riotgames",
  roblox: "roblox",
  netflix: "netflix",
  spotify: "spotify",
  youtube: "youtube",
  twitch: "twitch",
  prime: "primevideo",
  google: "google",
  microsoft: "microsoft",
  slack: "slack",
  zoom: "zoom",
  notion: "notion",
  github: "github",
  dropbox: "dropbox",
  vpn: "nordvpn",
};

export function getIconSlug(subcategoryId: string): string | undefined {
  return ICON_SLUGS[subcategoryId];
}
